/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gf.app.covid.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ruth
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    public Integer getCurso() {
        return Integer.parseInt(Curso.getText());
    }

    public void setCurso(JTextField Curso) {
        this.Curso = Curso;
    }

    public JCheckBox getDiarrea() {
        return Diarrea;
    }

    public void setDiarrea(JCheckBox Diarrea) {
        this.Diarrea = Diarrea;
    }

    public JCheckBox getDolor() {
        return Dolor;
    }

    public void setDolor(JCheckBox Dolor) {
        this.Dolor = Dolor;
    }

    public JButton getEnviar() {
        return Enviar;
    }

    public void setEnviar(JButton Enviar) {
        this.Enviar = Enviar;
    }

    public JCheckBox getFiebre() {
        return Fiebre;
    }

    public void setFiebre(JCheckBox Fiebre) {
        this.Fiebre = Fiebre;
    }

    public JLabel getId() {
        return Id;
    }

    public void setId(JLabel Id) {
        this.Id = Id;
    }

    public JCheckBox getOlfato() {
        return Olfato;
    }

    public void setOlfato(JCheckBox Olfato) {
        this.Olfato = Olfato;
    }

    public JCheckBox getTos() {
        return Tos;
    }

    public void setTos(JCheckBox Tos) {
        this.Tos = Tos;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Id = new javax.swing.JLabel();
        Fiebre = new javax.swing.JCheckBox();
        Tos = new javax.swing.JCheckBox();
        Diarrea = new javax.swing.JCheckBox();
        Dolor = new javax.swing.JCheckBox();
        Olfato = new javax.swing.JCheckBox();
        Enviar = new javax.swing.JButton();
        Curso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Id.setText("Id");

        Fiebre.setText("Fiebre");
        Fiebre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiebreActionPerformed(evt);
            }
        });

        Tos.setText("Tos");

        Diarrea.setText("Diarrea");

        Dolor.setText("Dolor");

        Olfato.setText("Olfato");

        Enviar.setText("Enviar");

        Curso.setText("curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Enviar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Fiebre)
                                .addGap(18, 18, 18)
                                .addComponent(Tos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Diarrea)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dolor)
                        .addGap(18, 18, 18)
                        .addComponent(Olfato)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Id)
                    .addComponent(Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fiebre)
                    .addComponent(Tos)
                    .addComponent(Diarrea)
                    .addComponent(Dolor)
                    .addComponent(Olfato))
                .addGap(54, 54, 54)
                .addComponent(Enviar)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FiebreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiebreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiebreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Curso;
    private javax.swing.JCheckBox Diarrea;
    private javax.swing.JCheckBox Dolor;
    private javax.swing.JButton Enviar;
    private javax.swing.JCheckBox Fiebre;
    private javax.swing.JLabel Id;
    private javax.swing.JCheckBox Olfato;
    private javax.swing.JCheckBox Tos;
    // End of variables declaration//GEN-END:variables
}
